source "https://rubygems.org"

gem "discordrb", "~> 3.5"
gem "dotenv", "~> 3.1"
gem "sorbet", :group => :development
gem "sorbet-runtime"
gem "tapioca", require: false, :group => [:development, :test]
