[package]
name = "discordbot"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "discordbot"
path = "main.rs"

[dependencies]
dotenv = "0.15"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }